title = "CTF講義"

problems = [
  { name = "test", title = "[Misc] Test Problem (オリジナル)" },
  { name = "rotten", title = "[Crypto] Rotten Text (オリジナル)"},
  { name = "netcat", title = "[Misc] what's a net cat? (picoCTF)"},
  { name = "ghost", title = "[Web] Ghost!? (オリジナル)"},
  { name = "valley", title = "[OSINT] Valley (オリジナル)" },
  { name = "valley2", title = "[Forensics] Valley 2 (オリジナル)" },
  { name = "rsa", title = "[Crypto] RSA Encryption (オリジナル)" },
  { name = "bin", title = "[Reversing] Hello, Binary! (オリジナル)" },
]
